name: exemplo inicial

on: 
  workflow_dispatch:
  
env: 
  global_var: "sou uma variável global"

jobs: 
    job1:
      runs-on: ubuntu-latest

      steps:
        - name: escreve x
          run: echo "x"

        - name: test curl
          run: curl https://jsonplaceholder.typicode.com/posts
        
    job2: 
      needs: job1 
      runs-on: ubuntu-latest
      steps:
        - name: escreve y 
          run:  echo "y"

    job3: 
      needs: [job1, job2]
      runs-on: ubuntu-latest
      steps:
        - name: escreve z
          run: echo "z"
     
    independent-job: 
      runs-on: ubuntu-latest
      steps: 
        - name: atribuir valor a variável dinamica
          run: echo "dynamic_var=bla" >> $GITHUB_ENV

        - name: escreve o valor das variáveis
          run: |
            echo "a"
            echo "${{ env.global_var }}"
            echo "${{ env.job_var }}"
            echo "${{ env.step_var }}"
            echo "${{ env.dynamic_var }}"
        
          env: 
            step_var: "sou uma var do step"
      
      env:
        job_var: "sou uma var do job"
      
      
