name: Semantic release test


on: 
  push: 
    branches: 
      ["main"]

  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

permissions:
  contents: write
    
jobs: 
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest version of code
        uses: actions/checkout@v3

      - name: escreve x
        run: echo "x"
      
      - name: move .releaserc file
        run: mv .github/.releaserc .

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
      
      - name: Dry run to get the next release version
        id: tag_version
        run: |
          export NEXT_TAG_VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')
          echo "new_tag_version=${NEXT_TAG_VERSION}" >> $GITHUB_OUTPUT

      - name: Run semantic-release
        run: npx semantic-release
  
  publish:
    needs: release
    if: ${{ needs.release.outputs.new_tag_version != '' }}
    runs-on: ubuntu-latest
    steps: 
      - name: Print version
        run: echo ${{ needs.release.outputs.new_tag_version }}
  